---
title: "Policy Writing"
site: distill::distill_website

---


### [Fear or knowledge: The impact of graphic cigarette warnings on tobacco product choices](https://cepr.org/voxeu/columns/fear-or-knowledge-impact-graphic-cigarette-warnings-tobacco-product-choices)
  - ***VoxEU Column***, with Donald Kenkel, Alan Mathios, Grace Phillips, Hua Wang, Sen Zeng. 23 September, 2023

### [Social health insurance schemes](https://global.oup.com/academic/product/india-public-finance-and-policy-report-9780190121150?cc=us&lang=en&)
  - ***India Public Finance and Policy Report***, Oxford University Press, 2020, with Arjun Bedi, Arpita Chakraborty, Sisir Debnath, Anagaw Derseh Mebratie, Pradeep Panda, E. van de Poel, Wameq Raza, Frans Rutten, Zemzem Shigute, Robert Sparrow, Revathy Suryanarayana and Getnet Alemu Zewdu. Edited by J. Jalan, S. Marjit and S. Santra.

### [Designing India's national healthcare protection: Challenges and opportunities](https://www.ideasforindia.in/topics/human-development/designing-india-s-national-healthcare-protection-challenges-and-opportunities.html)
  - ***Ideas for India***, August 27, 2018, with [Tarun Jain](https://sites.google.com/virginia.edu/tarunjain/home?authuser=0){target="_blank"}, [Sisir Debnath](https://hss.iitd.ac.in/faculty/sisir-debnath){target="_blank"} and Dibya Mishra.

### [Common tongue? How mother tongue instruction influences education](https://www.ideasforindia.in/topics/macroeconomics/common-tongue-how-mother-tongue-instruction-influences-education.html)
  - ***Ideas for India***, February 27, 2017, with [Tarun Jain](https://sites.google.com/virginia.edu/tarunjain/home?authuser=0){target="_blank"}.


