---
title: "Research"
site: distill::distill_website

---
## Publications

##### [**Alcohol Ban and Crime: The ABC's of the Bihar Prohibition**](https://www.journals.uchicago.edu/doi/abs/10.1086/725452)

With [Kalyani Chaudhuri](https://economics.ucdavis.edu/people/kalyanic){target="_blank"}, [Natasha Jha](https://tci.cornell.edu/people/natasha-jha/){target="_blank"} and [Mrithyunjayan Nilayamgode](https://economics.virginia.edu/people/profile/mn4yk){target="_blank"}.  
**Forthcoming at Economic Development & Cultural Change**

<details><summary><b>Abstract</b></summary> We study the relationship between alcohol consumption and crime, following an alcohol prohibition in Bihar in 2016. Using a difference-in-differences approach, we explore the differential effects of alcohol on different crime types. We find that the prohibition led to a 0.22 standard deviation point reduction in reported violent crimes without significantly impacting nonviolent crimes. Heterogeneity tests reveal stronger effects in interior districts and those with higher baseline alcohol consumption or fewer religious restrictions on alcohol consumption. </details>

## Working Papers


##### **Opioid Supply, Trade Liberalization Shocks, and Infant Health Outcomes** 

*Job Market Paper*

<details><summary><b>Abstract</b></summary> This paper examines the interaction of factors affecting opioid supply and opioid demand and their impact on neonatal health outcomes. I exploit variation in the triplicate status of states in 1996 and a county-level trade liberalization shock as natural variations for opioid supply and demand, respectively. The results indicate that the counties that experienced high opioid demand and supply had an increase in the incidence of preterm births and births with low birth weight. Specifically, relative to the baseline mean, the preterm birth rate increased by 3.8\%, and the rate of births with low birth weight increased by 5\% in those counties experiencing high opioid supply and increased economic distress. I also find that trade liberalization shocks independently led to a significant decrease in the incidence of preterm births and births with low birth weight suggesting that there might be positive maternal selection into fertility. In contrast, the triplicate status of states, by itself, does not significantly explain infant health outcomes. My findings indicate that the triplicate laws had a protective effect on infant health in counties experiencing higher economic distress and therefore, higher opioid demand. </details>



 **Presentations: Southern Economic Association Annual Meeting, 2023**



##### **The Long-Run Impact of Federal Income Support on Criminal Involvement and Risky Behavior of Adults** 

<details><summary><b>Abstract</b></summary> There is now a good deal of evidence that conditional and unconditional cash transfers benefit individuals and families in a number of ways. But, could cash transfers to families pay for themselves over time by lowering crime and the ensuing high public costs of incarceration of the next generation? I study this question within the context of the Earned Income Tax Credit, an anti-poverty tax credit program in the US that substantially increased the income of low- and moderate-income working families. I use a reduced-form instrumental variable strategy that exploits tax credit variations arising out of federal and state EITC policies to study the impact of total EITC exposure during childhood on adult outcomes. I find that a \$1000 increase in total EITC exposure between the ages of 0 and 18 leads to a 1.2 percent decrease in the probability of engaging in criminal behaviors during adulthood. I also observe substantial reductions in an individual's propensity to engage in other risky health behaviors including binge drinking and heavy smoking. With respect to mechanisms, I find evidence that not only are individuals less likely to commit crimes but more likely to engage in productive work activities during adulthood. I also provide novel evidence that higher instrumented EITC leads to a lower probability of working while individuals are still in school and experience better neighborhood attributes during childhood and young adulthood.  </details>

**Presentations: APPAM Fall Research Conference 2023 (Upcoming), Southern Economic Association Annual Meeting 2021, Population Association of America Annual Meeting 2021**

##### **Comprehensive PDMP Mandates, Naloxone Access Laws, and Home Removals** 
With Sarah Beth Barnett, Mary Blain Grist, [Yuhua Bao](https://vivo.weill.cornell.edu/display/cwid-yub2003).


### <u> Research on Tobacco Harm Reduction </u>
##### **Fear or Knowledge? The Impact of Graphic Cigarette Warnings on Tobacco Product Choices**
With Donald Kenkel, Alan Mathios, Grace Phillips, Hua Wang, and Sen Zen. [**NBER Working Paper 31534**](https://www.nber.org/papers/w31534)

<details><summary><b>Abstract</b></summary> Requiring graphic warning labels (GWLs) on cigarette packaging has become a highly contentious unresolved legal battle. The constitutionality depends, in part, on the likely impact of GWLs on smoking decisions, and whether they generate knowledge as opposed to emotional reactions against smoking. Using an online discrete choice stated preference experiment we compare tobacco choices (cigarettes, e-cigarettes, quitting) for those presented with a GWL versus the currently existing label. We find the fraction of individuals choosing cigarettes to be lower and quitting higher for the GWL group. Our findings reveal that the differences between groups were primarily driven by the evocation of fear and disgust rather than an improvement in health knowledge related to the GWL. The discrete choice experiment also provides new evidence on how cigarette prices, e-cigarette prices, and policy-manipulable e-cigarette attributes such as e-cigarette warning labels, and flavor availability influence tobacco product choices. </details>



##### **Understanding the Demand-Side of an Illegal Market: Prohibition of Menthol Cigarettes**

With Donald Kenkel, Alan Mathios, Grace Phillips, Hua Wang, and Sen Zen.


##### **COVID and Smoking: Evidence from India**

With Donald Kenkel, Alan Mathios, and Hua Wang

**Presentations: 12th Annual Conference of the American Society of Health Economists 2023, Tobacco Online Policy Seminar 2023 **


##### **Just What the Doctor Ordered? The Benefits and Costs of E-Cigarette Regulation in Australia**
With Donald Kenkel, Alan Mathios, Grace Phillips, Hua Wang, and Sen Zen.


##### **Cigarette and Heated Tobacco Product Use in Japan: The Role of Flavored Products**

With Donald Kenkel, Alan Mathios, Grace Phillips, Hua Wang, and Sen Zen.

**Presentations: 11th Annual Conference of the American Society of Health Economists 2022**

### <u> Other Working Papers </u>


##### **Out-of-Pocket Costs and Initiation of HCV Treatment among Medicare Beneficiaries**

With Hao Zhang, Shashi Kapadia, and Yuhua Bao.

**CHERISH Pilot Grant Project**

**Presentations: 12th Annual Conference of the American Society of Health Economists 2023**


##### **Opioid policies and Adverse Childhood Experiences: A Systematic Review**

With with Sarah Beth Barnett, Mary Blain Grist, and Yuhua Bao.



##### **Recreational Marijuana Laws and Intimate Partner Violence**

With Alberto Chong and Michele Baggio

##### **Gender Differences in Tertiary Healthcare Utilization: Evidence from India**

With Tarun Jain and Natasha Jha.


##### **Like Mother, Like Daughter? The Impact of Mother’s Work Experience on Daughter’s Educational and Employment Aspirations: Evidence from WWII**

With Natasha Jha, Giulia Olivero, and Meredith Welch




